// Web/personal-site/src/app/components/github-card/github-card.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { GithubRepo } from 'src/app/models/githuRepo';

@Component({
  selector: 'github-card',
  templateUrl: './github-card.component.html',
  styleUrls: ['./github-card.component.scss']
})
export class GithubCardComponent implements OnInit {
  @Input() repo: GithubRepo;
  constructor() { }

  ngOnInit() {
  }

  openLink(args:any){
    console.log(args);
    window.open(args);
  }

}

<div class="card repo-card">
    <div class="card-body" (click)="openLink(repo.html_url)">
      <h5 class="card-title">{{repo.name}}</h5>
      <p class="card-text">{{repo.description}}</p>
      <div class="row">
        <div class="col-md-4 text-center"><mdb-icon fas icon="exclamation-circle"></mdb-icon>   {{repo.open_issues}}</div>
        <div class="col-md-4 text-center"><mdb-icon fas icon="star"></mdb-icon>   {{repo.stargazers_count}}</div>
        <div class="col-md-4 text-center"><mdb-icon fas icon="code-branch"></mdb-icon>   {{repo.forks}}</div>
      </div>
    </div>
  </div>

// Web/site-v2/personal-site/components/github-card.vue
<template>
  <b-card @click="navigate(repo.html_url)" :title="repo.name" :sub-title="repo.description" bg-variant="dark" text-variant="white" class="tile text-center" >
      <v-container fluid>
        <v-row>
            <v-col>
                <v-icon>mdi-alert-circle-outline</v-icon>
                <p>{{repo.open_issues}}</p>
            </v-col>
            <v-col>
                <v-icon>mdi-star</v-icon>
                <p>{{repo.stargazers_count}}</p>
            </v-col>
            <v-col>
                <v-icon>mdi-source-branch</v-icon>
                <p>{{repo.forks}}</p>
            </v-col>
        </v-row>
      </v-container>
  </b-card>
</template>

<script>
export default {
  props: {
      repo: Object
  },
  methods: {
    navigate(url) {
      window.open(url);
    }
  }
}
</script>

<style>
.tile:hover {
    transform: scale(1.05);
}
</style>
